[build]
  command = "npm run netlify:build"
  functions = "lambda"
  publish = "__sapper__/export"

[[redirects]]
## Asset pages are not pre-generated
  from = "/collections/*"
  to = "/index.html"
  status = 200